### PR TITLE
Project Refactor pt. 2

### PR DESCRIPTION
**Pull request by ricardofbarros**
Continuing from #9.

 Yes @pmvrmc , it's a start  :P I really don't like the logo I did, but it's way better than having a [WIP] and a empty README so thank you :)

Exactly @pmvrmc  [right on point!](https://github.com/shelf-js/shelf/blob/full_rework/examples/storage.js) :+1:

For me it's ready for merge and a major version bump after I finish the postinstall script stuff to support >=0.10

I'll try to have it done today so we can merge your fantastic work! I'll try as well reach @JGAntunes through telegram just so he can give any thought on this.

### CODE REVIEW

**Comment by ricardofbarros** [comment]
Sup homies @JGAntunes @pmvrmc ,

So I just pushed a [new repo to handle our problems with the node.js version comparability with ES6 ](https://github.com/shelf-js/shelf-bc), If you find anything there you can improve open a PR or a issue.

I also added a `postinstall` script here.

**Comment by ricardofbarros** [comment]
After everything is reviewed, @pmvrmc please squash my commits into your commit.

**Comment by pmvrmc** [comment]
Hey! Sorry for the delayed response.

I just made a fix onto shelf.js, there was a wrong required being made.

Also I tried running the example in node 4 and everything works.
However when I changed my node version to 0.12.10 and reinstalled the dependencies I noticed a couple bugs:
- The src folder is created but this breaks the index.js (which requires ./lib/shelf)
- After I adapt the examples to es5 I still can't run it, it seems the transpilling did not occur :disappointed:  
  The src folder still contains lots of "const" for example.

@ricardofbarros could you try to solve this before we merge back into master?

**Comment by ricardofbarros** [comment]
Hey @pmvrmc I just solved the problem and simplified the process as well, I pushed the fix into `shelf-bc`. Could you test again?

**Comment by ricardofbarros** [comment]
Btw the way I tested is:

> `rm -rf node_modules`
> `npm i` (while in 0.12)

Dunno if that's how you test it. @pmvrmc the first solution didn't work because it missed the babel-es2015-preset module under the project dir, but that's all fixed now I think.

**Comment by pmvrmc** [comment]
Hi @ricardofbarros! Sorry for the delay, the weekend was CA-RA-ZY :boom: 

Yeah I tried removing the dependencies and installing node 0.12 or 4 (I used nvm).

Now the code transpilles fine, but I still get errors when running, because the node_modules dependencies are using ES6. Is there anything I might be doing wrong?

> `rm -rf node_modules`
> `npm i` (while in node 0.12)
> `node examples/index.js` (edited the examples to use var instead of const)

Nevertheless I get "SyntaxError: Use of const in strict mode." `projects/shelf/node_modules/joi/lib/index.js:5
const Hoek = require('hoek');`

**Comment by ricardofbarros** [comment]
Hey @pmvrmc. This is a pain in the ass :sob: 

@JGAntunes had an idea to solve this issue. Use different major versions.

`1.x.x` would support <=0.12.\* 
`2.x.x` would support > 0.12

We could use `shelf-bc` to help release process, transpiling the code to support <=0.12.*

My only problem with this is that you would break the shelf API on some point, because you would need to use `joi@6` (I think?) on the `1.x.x` and on the `2.x.x` you would like to use the latest joi. And this will inevitable break something. 

For instance you would use some feature on `joi@9.0.0` on the shelf's latest release, so you would publish those changes to `2.x.x` then you would transpile the code for `1.x.x` but we had to remove this specific feature because `joi@6` doesn't have it. Am I making any sense at all ?

So I've gathered a few options we have to tackle this problem:
- **use versioning to support different engine versions**
- **"downgrade" joi version to a ES5 compliant**
- **transpile `shelf/lib` and `shelf/node_module/joi`??** (sound a bit crazy, but it would work, I just don't know how much time it would take to install shelf as dependency lol)

The best option we have right now, on my opinion, is @JGAntunes idea. What do you think of this @pmvrmc ? Maybe you have a better idea to solve this problem

**Comment by JGAntunes** [comment]
Hey guys! Really sorry about the delay on this.

So, with all the modules stuff I think our best option will be to use different major versions and npm tags for publishing (and document it accordingly). What do you think @pmvrmc? My only question with this method is if you are going to maintain two codebases or only one and transpile it to the ES5 release (with a pre-publish hook or something like that).

**Comment by ricardofbarros** [comment]
@JGAntunes maintaining two code bases sounds very painful :sob: and the pre-publish hook doesn't seem to me the best option available.

With the pre-publish hook you will have several problems, for instance with merge conflicts.
One that comes up on top of my head is the `package.json` dependencies versions. 

You will need to use different dependencies versions for the different shelf versions. If you release a new shelf version with a new dependency that only works on ES6 and publish it, running then the pre-publish hook which will transpile the code and publish it, without prior testing. I don't like the idea of releasing stuff untested. 

But what if you run the test script on the pre-publish hook it will work right?

No, it won't work because you have your tests written in ES6, even if you use ES5 tests it still won't work because guess what you still have a new dependency that won't work on 0.12. Pain in the ass, right?

We need a release flow for shelf to tackle this issue or look at different options like the Joi version dowgrade. 

Tell me something guys, since you are pro-hapi maybe you know. What are the biggest differences on `Joi@6` and `Joi@7`, excluding that Joi@6 is written on ES5, talking about the API itself. 

If you guys don't like the idea of using an outdated Joi I've come with a release flow for your idea (@JGAntunes)  and ofc I'm open for suggestions.

### Release flow

The tests need to be written as ES5 compliant also the devDependencies. We have 2 "active" branches, `master`and `1.x.x`. We need to have a `transpile` npm script.

We want to deliver a new feature so we do the following:
- **Create feature branch for the new `2.x.x` release**
- **Write the new feature with the test for it**, test written in ES5
- **Commit**, pre-commit will run `lint` and `test` scripts
- **Go to `master` repo and rebase the feature branch**
- **Publish new version, `2.x.x`**
- **Create tmp local branch from `master` and run the `transpile` script**
- **Take `lint` from the pre-commit array** because babel will violate standard for sure :hammer: :hammer: :hammer:  (Don't judge me!)
- **Commit changes** 
- **Change to branch `1.x.x` and rebase this tmp local branch**, this will push the package.json changes to the top
- **???**
- **Profit!**

This release flow will cover our needs. It's a very manual process, maybe we can find a more efficient way to achieve this behaviour

**Comment by JGAntunes** [comment]
@ricardofbarros  okay, I fully agree with the 2 code base issue but I think you're going to need at least a different package.json for both, because, as you've said, you're going to have to handle different dependencies, different work flows (which might imply different npm scripts) and maybe more stuff we're not even considering.

As for the process you've described I think we can automate it through npm/bash scripts. Going to search a bit on this topics to see what I can find.

**Comment by ricardofbarros** [comment]
Yeah @JGAntunes that was what I was saying we will have 2 different package.json, thus the rebase to keep the commit of the package.json's changes always at the top of the history.

And yes I agree automation of the workflow through npm/bash scripts would be a good bet.

**Comment by JGAntunes** [comment]
As for the tests, why not transpiling them also @ricardofbarros?

**Comment by ricardofbarros** [comment]
Hmm @JGAntunes we could, but I don't see any benefit of writing ES2015 tests, and if we did that we also had to check dev dependencies if they are compatible with ES5. 

I think I just wanted to take the easiest route, feelin' kinda lazy lately :smile:

**Comment by ricardofbarros** [comment]
But if you feel strong about writing ES2015 test, I won't oppose that decision.

**Comment by JGAntunes** [comment]
For me it's only about the mindset we have while working, I mean this way we could avoid switching between ES5 and ES2015 all the time.

**Comment by ricardofbarros** [comment]
Okay, good point, that makes sense. But if we do that I still think we need to use the same devDeps version on both shelf's versions.

**Comment by pmvrmc** [comment]
Hi guys,

If we go forward with this idea I feel that the process @ricardofbarros described can help us "split" codebases.

Nonetheless, aren't we over complicating things? Why don't we just support ES6 in the new release and if someone wants to use ES5 then they should use the old release (that we would deprecate in the future and only make minor bug fixing).

What do you think?

**Comment by JGAntunes** [comment]
@pmvrmc you're suggesting then maintaining two different code bases?

**Comment by ricardofbarros** [comment]
Yo,
ES6 version is top priority for sure, but I don't see why we don't support ES5 as well, because there is a ridiculous amount of companies that sill use 0.10 and 0.12.

**Comment by ricardofbarros** [comment]
And that release process gives priority to `2.x.x` as for the `1.x.x` release is optional.

**Comment by JGAntunes** [comment]
Squashed everything and merged. Hope you don't mind @pmvrmc ;)

**Comment by JGAntunes** [comment]
So, correct me if I'm wrong, but I think this will be the 2.0.0 release, am I right? @ricardofbarros @pmvrmc

**Comment by pmvrmc** [comment]
Its fine @JGAntunes :)

Yeah, 2.0.0! Lets ready everything for Shelf official launch :rocket:

**Pull request merged**
