### PR TITLE
Project Refactor

### PR DESCRIPTION
**Pull request by pmvrmc**
Hi guys,

Refactored the whole project, removed unimplemented features, cleaned a lot of code, added tests (98.59% cc) and moved to ES2015. Also "classes" now use the object factory pattern.

Btw, I removed the hget method as there is no hset method yet. We can create some tickets with these kind of missing features.

Tell me what you think of it =)

Still working on a new README...

### CODE REVIEW

**Comment by JGAntunes** [comment]
Awesome! Will try to review it tomorrow. Nice work :smile:

**Comment by ricardofbarros** [comment]
Nice work! I noticed you changed the way storage is passed down to the schema affecting the way the developers creates a new schema model.

The first thought that came to my mind when I saw your example was of a flux implementation, where the developer implements it's own store (storage) and extend from there.

I don't have anything against this, but I would prefer the simpleness over configuration.
You know when the developers just requires the model and start describing it's data model.

I guess you guys will disagree with me because I prefer express over hapi and you clearly prefer hapi over express, so I could be biased. But I would love to hear some thoughts from both of you @JGAntunes @pmvrmc 

But overall great work @pmvrmc! :) :+1:

**Comment by ricardofbarros** [comment]
If we're going with ES2015 features we need to specify on package.json the [engine](https://docs.npmjs.com/files/package.json#engines) this package can work on.

My wild guess (without seeing any docs) should be something like `>=4.0.0` 

Btw @pmvrmc  if you merge this muzzley managers that use shelf will stop working or are you guys using newer node.js versions than 0.10 ? xD

One thing we could do to support lower engine versions like 0.12 and 0.10 is to use a `postinstall` script that would check the node.js version on the machine and if it was lower than 4.0.0 we could use a code transpiler like babel

**Comment by pmvrmc** [comment]
Thanks for the feedback!

Let me see If I understood correctly your first comment @ricardofbarros :

You are saying for us to allow users to "extend/create" schemas directly from Shelf even if it is not instantiated, right? And somewhere else on the code instantiate Shelf with the DB connection (or any other storage).

This seems reasonable, nevertheless the schema extension without a valid connection to the storage holds no value, it's just objects with boilerplates for name, props and keys.

The name and keys only have value if you want to store the objects.
If you're interested only on the props you should create objects "the normal way" using an object factory that on the constructor validates the params.

Besides, as you said, having the configuration right there near the schema increases readability and adapts to wider range use-cases.

Regarding the engine, yeah you're totally right, we should include version as something like that.
Using a transpiler seems a really cool feature and something we should definitely create an issue for!

Regarding versioning, I think we should make a minor bump (as we finish details to make the 1.0) to not break compatibility. But there is no issue on managers, the ones using Shelf were built using node 4.x =)

Btw: I am thinking on renaming "model" to "schema" to make clearer, what do you think?

**Comment by ricardofbarros** [comment]
Renaming `model` to `schema` seems appropriate, so go ahead :+1: if it's fine by @JGAntunes.

Yeah you're totally right on some parts, when I said it resembled me redux wasn't a critic but actually a compliment, but what I don't like is let developers create their own flavour of a [storage instance](https://github.com/shelf-js/shelf/blob/0579a3247af511782cbf75fe4a252343a3335013/examples/storage.js). 

We should at least give them a way to create a store instance like `redux`. So all storage instance would be uniform, easier to debug when the issues come because some developer did some weird bat shit crazy it's storage instance and we can't figure it out. and believe me it will happen.

One thing I like about your implementation of the [storage instance](https://github.com/shelf-js/shelf/blob/0579a3247af511782cbf75fe4a252343a3335013/examples/storage.js) is that  I found it very clean and straightforward on the eyes and that's a big plus.

So what you think on doing a interface for developers so they can create their own storage? 

Do you agree with my vision or do you have a different vision on this matter @pmvrmc ?

**Comment by pmvrmc** [comment]
Oh I think I get it, something like moving the [example storage instance](https://github.com/shelf-js/shelf/blob/0579a3247af511782cbf75fe4a252343a3335013/examples/storage.js) directly into Shelf.

Seems reasonable, will look into it and try to have a working example in the next couple of days ;)

**Comment by ricardofbarros** [comment]
Yeah exactly, @pmvrmc.

I will try help on the postinstall script with the babel, but I don't promise anything as I have massive pain in my wisdom teeth and I need to have it removed when I get back to PT, so let's see how that plays out.

**Comment by ricardofbarros** [comment]
Yo @pmvrmc, can you push your changes to a branch on shelf ? instead of a fork. I think now you have push permissions, if you don't just ping me here.

**Comment by pmvrmc** [comment]
Sure, let me get home and I'll do it

**Comment by ricardofbarros** [comment]
Great, thanks @pmvrmc

**Comment by pmvrmc** [comment]
@ricardofbarros I'm getting 403 permission denied when trying to push the new branch to the remote. Probably related to what you said before about push permissions

**Comment by ricardofbarros** [comment]
Hey @pmvrmc , strange :/ Sorry, could you try again?

**Comment by pmvrmc** [comment]
Thanks, it done. Pushed it to branch [full_rework](https://github.com/shelf-js/shelf/tree/full_rework).

Added a improved REAME, tell me what you think of it.

Also made the changes related to the Storage, was this what you were thinking of @ricardofbarros ?

**Comment by ricardofbarros** [comment]
Closing in favor of #10

**Pull request closed without merging**
