### PR TITLE
go for 100 coverage and make tests prettier

### PR DESCRIPTION
**Pull request by ricardofbarros**
Also I restored a file path I had changed: `lib/shelf` to `index`

### CODE REVIEW

**Comment by pmvrmc** [comment]
Great job @ricardofbarros!

I like what you did, restoring the index.js to the Shelf itself :+1: 

In my opinion lets merge and create a release, what you think @JGAntunes ?

**Comment by ricardofbarros** [comment]
I think for the `2.x.x` we are ready to release

**Comment by JGAntunes** [comment]
:+1: pretty cool! Didn't know proxyquire.

**Comment by JGAntunes** [comment]
You can bump it and release it @ricardofbarros

**Comment by pmvrmc** [comment]
@ricardofbarros could you publish 2.0.0 to npm?

**Pull request merged**
